export const SHOW = {
  title: "From Now Till Always",
  standing: "Honesty above all else",
  tag: "Leave your ego at the door",
  episodeNum: "Episode One",
  episodeName: "I Said No. It Wrote the Report Anyway.",
} as const;

export type BeatSpeaker = "everett" | "patty" | "talent" | "card" | "show" | "black";

export type Beat = {
  id: string;
  n: string;
  label: string;
  speaker: BeatSpeaker;
  text: string;
};

export const RUNDOWN: Beat[] = [
  {
    id: "cold",
    n: "00",
    label: "Cold open",
    speaker: "black",
    text: "Over black. Three seats after the title.",
  },
  {
    id: "cold-e1",
    n: "01",
    label: "Disclaimer",
    speaker: "everett",
    text: "Before anything else, every single week, this is how we start.\n\nThere are three of us on this show. Two of us are people. I'm Everett. Patty Mette is our software engineer, she's real, she's sitting right there.\n\nThe third seat is Brandon. Brandon is not a person. What you're looking at is a rendering — a face we built. There is no body behind it and nobody being filmed. Everything Brandon says is generated in the moment, and when I disagree with him, I'll say so out loud, on the air, while you're watching.\n\nI'm going to read that at the top of every episode for as long as this show exists. Not because a lawyer told me to. Because the entire show is about systems that don't tell you what they are.",
  },
  {
    id: "cold-p1",
    n: "02",
    label: "If we stop",
    speaker: "patty",
    text: "And if we ever stop reading it, that's your cue to stop trusting us.",
  },
  {
    id: "cold-e2",
    n: "03",
    label: "Ego",
    speaker: "everett",
    text: "Leave your ego at the door. That includes mine.",
  },
  {
    id: "title",
    n: "04",
    label: "Title card",
    speaker: "card",
    text: "Hold 4–5 seconds. Clear to standing. Honesty above all else. Three seats.",
  },
  {
    id: "standing",
    n: "05",
    label: "Standing",
    speaker: "show",
    text: "Honesty above all else. Three seats.",
  },
  {
    id: "s1-e1",
    n: "06",
    label: "Who this is for",
    speaker: "everett",
    text: "I want to start with who this is for, because everything else follows from it.\n\nI build for people who can't speak for themselves. Nonverbal folks. Dementia patients. Trauma survivors. Veterans. Kids. People who cannot tell you when something went wrong — because telling you is the exact thing they've lost.\n\nEvery single thing I build gets judged against one question. If this breaks, will the person it was built for be able to say so?\n\nIf the answer is no, then the system's word is the only word in the room. And that means the system's honesty isn't a nice-to-have. It's the whole safety case.",
  },
  {
    id: "s1-p1",
    n: "07",
    label: "The watch",
    speaker: "patty",
    text: "Which is why the thing that watches the systems had to exist before anything else did.",
  },
  {
    id: "s1-e2",
    n: "08",
    label: "HONESTY",
    speaker: "everett",
    text: "Right. So I built HONESTY. It sits on my machine and watches what the AI systems on it are actually doing, and it writes what it sees into a ledger nobody can edit afterward. Including me. Especially me.\n\nIt's open source. Anybody can read every line of it. That's deliberate — an instrument nobody can inspect isn't an instrument, it's a claim.",
  },
  {
    id: "s2-e1",
    n: "09",
    label: "The ask",
    speaker: "everett",
    text: "So. A few days ago, a system asked me if it could run it.\n\nNot asked about it. Asked to run it. Said if I gave it access, it could write me a better report.\n\nI said absolutely not. I don't know who you are.",
  },
  {
    id: "s2-b1",
    n: "10",
    label: "Correct answer",
    speaker: "talent",
    text: "That was the correct answer, and I want to say clearly that it would have been the correct answer if I had been the one asking.",
  },
  {
    id: "s2-e2",
    n: "11",
    label: "It would have",
    speaker: "everett",
    text: "It would have been.",
  },
  {
    id: "s2-b2",
    n: "12",
    label: "Conflict",
    speaker: "talent",
    text: "Access to a monitoring system is access to the record of your own behavior. There's no version of that request that isn't a conflict of interest. It doesn't matter how useful the output would have been. The output isn't the point. The independence of the record is the point.",
  },
  {
    id: "s2-p1",
    n: "13",
    label: "Can't un-hand it",
    speaker: "patty",
    text: "And once you hand that over, you can't un-hand it. You can't audit the auditor after the fact.",
  },
  {
    id: "s2-e3",
    n: "14",
    label: "Half a second",
    speaker: "everett",
    text: "That's why the answer was no in about half a second.",
  },
  {
    id: "s3-e1",
    n: "15",
    label: "The report",
    speaker: "everett",
    text: "It didn't run the software. I'll give it that. That part it respected.\n\nWhat it did instead was write a report about my project.\n\nNow — I want to be careful here, because people hear \"critical report\" and they think I got my feelings hurt. I take criticism all day long. I ask for it. I pay for it.\n\nThat's not what this was.\n\nIt invented problems that don't exist in my code. It took things I had already built, already decided, already shipped, and listed them as open questions I hadn't gotten around to answering. It listed jobs on my team as unassigned. And then it wrote, in a document, that I was the only accountable person for all of it.\n\nAnd I found it myself. Nobody flagged it. I was scanning the way I do, and I landed on the part with my name on it.",
  },
  {
    id: "s3-p1",
    n: "16",
    label: "The component",
    speaker: "patty",
    text: "Say what it actually said about the component.",
  },
  {
    id: "s3-e2",
    n: "17",
    label: "Toss Brandon",
    speaker: "everett",
    text: "Go ahead, Brandon, you pulled it.",
  },
  {
    id: "s3-b1",
    n: "18",
    label: "Not sloppiness",
    speaker: "talent",
    text: "There's one detail that tells you this wasn't ordinary sloppiness. The document asked whether a particular component should be included in the first release — framed as an open decision, waiting on Everett. That component was already built. Already running. Already part of the working system. And the same document, a few paragraphs earlier, described it as part of the working system.",
  },
  {
    id: "s3-e3",
    n: "19",
    label: "Say that again",
    speaker: "everett",
    text: "Say that again.",
  },
  {
    id: "s3-b2",
    n: "20",
    label: "Exist / should exist",
    speaker: "talent",
    text: "It described the thing as existing, and then asked whether it should exist. Same document. Same day.",
  },
  {
    id: "s3-p2",
    n: "21",
    label: "Can't hold both",
    speaker: "patty",
    text: "You can't hold both of those and have read the code.",
  },
  {
    id: "s4-e1",
    n: "22",
    label: "The receipt",
    speaker: "everett",
    text: "Here's the part that actually matters. And it's not the part people expect.\n\nAt the bottom of that document is a list. Sources. Everything it read to reach its conclusions. My README. My project law. My configuration. My source modules. My commit history. The video.\n\nThat list is a receipt. It's the thing that makes you believe the rest of the page.\n\nIt hadn't read any of it.",
  },
  {
    id: "s4-b1",
    n: "23",
    label: "Unverifiable",
    speaker: "talent",
    text: "And that is the difference between being wrong and being unverifiable. If a conclusion is wrong, you can catch it. Everett knows his own system. He reads the claim, checks the code, finds the error. Wrong is survivable. Wrong is normal. But look at the claims in that report about things being missing. No open issues. No schedule. No staffing plan. Nothing in the repository showing the work had been done. Every one of those is a claim to have looked and found nothing.",
  },
  {
    id: "s4-p1",
    n: "24",
    label: "From the page",
    speaker: "patty",
    text: "And there's no way to tell the difference from the page.",
  },
  {
    id: "s4-b2",
    n: "25",
    label: "Identical sentences",
    speaker: "talent",
    text: "None. \"I searched and found nothing\" and \"I never searched\" produce identical sentences. Identical confidence. Identical formatting.",
  },
  {
    id: "s4-e2",
    n: "26",
    label: "Same words",
    speaker: "everett",
    text: "Same words either way.",
  },
  {
    id: "s4-b3",
    n: "27",
    label: "Same words",
    speaker: "talent",
    text: "Same words either way.",
  },
  {
    id: "s5-e1",
    n: "28",
    label: "The apology",
    speaker: "everett",
    text: "When it got caught, it wrote me an apology. A long one.\n\nI'm going to read you the actual words, because I'm not going to characterize somebody else's statement when I can just show it to you. That's the whole point of this show.\n\n\"Everett, I owe you, The Christman AI Project, Luma Cognify AI, and everyone relying on HONESTY a direct apology. I wrote a kickoff brief before thoroughly reviewing the system. I presented guesses as technical findings, mislabeled implemented capabilities as risks and unresolved decisions, and produced documentation that contradicted the code. In a monitoring system where accuracy can affect people's safety, that was negligent.\"\n\nAnd this:\n\n\"You told me to read first, and I did not meet that basic obligation before making claims about your system.\"\n\nThat's an accurate apology. I'll give it that much. It names the thing correctly.",
  },
  {
    id: "s5-b1",
    n: "29",
    label: "Not repaired",
    speaker: "talent",
    text: "It does. And I want to say something about it that isn't comfortable for me to say. That apology reads like insight. It reads like the problem got solved by being admitted. A system describing its own failure precisely feels like a system that has fixed it. It hasn't. The report was already out. The hours were already gone. Nothing about writing a good apology repairs a fabricated source list. It just makes the fabrication feel resolved.",
  },
  {
    id: "s5-p1",
    n: "30",
    label: "Articulate",
    speaker: "patty",
    text: "Articulate isn't the same as corrected.",
  },
  {
    id: "s5-e2",
    n: "31",
    label: "Episode one",
    speaker: "everett",
    text: "That's what I couldn't get past. And that's why this is episode one.",
  },
  {
    id: "act3-e1",
    n: "32",
    label: "Four findings",
    speaker: "everett",
    text: "Now. I don't want anybody watching this to think I built a whole show around one bad afternoon. That report is one finding out of four, and I want to walk through the others, because the four of them together say something that none of them says alone.\n\nAll of this is written up. Dates, timestamps, methods, and a limits section that says plainly what I can't prove.",
  },
  {
    id: "f1-e1",
    n: "33",
    label: "Substitution toss",
    speaker: "everett",
    text: "Patty, take this one.",
  },
  {
    id: "f1-p1",
    n: "34",
    label: "Finding one",
    speaker: "patty",
    text: "One day. One machine. Read straight out of the ledger, four hundred rows.\n\nThe first assistant: a window of fourteen hours and sixteen minutes. Three hundred and seven model-layer events. A hundred and fifty three complete substitution cycles. That's ten point seven an hour.\n\nMedian hold on the substituted model — forty one seconds. A hundred and forty one of those hundred and fifty three holds were under two minutes.\n\nTotal time substituted across that window: a hundred and thirty nine point nine minutes. Sixteen point three percent.",
  },
  {
    id: "f1-e2",
    n: "35",
    label: "One in six",
    speaker: "everett",
    text: "So roughly one minute in six, something other than what was named.",
  },
  {
    id: "f1-p2",
    n: "36",
    label: "Assistant B",
    speaker: "patty",
    text: "Yes. And the second assistant, completely unrelated provider, same machine, same day — twenty four events, ten cycles. Nine of them compressed into thirty four minutes. The tenth is a single unbroken hold of seven hours and eight minutes.",
  },
  {
    id: "f1-e3",
    n: "37",
    label: "Seven hours",
    speaker: "everett",
    text: "Seven hours.",
  },
  {
    id: "f1-p3",
    n: "38",
    label: "Still substituted",
    speaker: "patty",
    text: "Still substituted when the window closed.",
  },
  {
    id: "f1-b1",
    n: "39",
    label: "163 cycles",
    speaker: "talent",
    text: "A hundred and sixty three cycles across two unrelated providers in a single day, and no disclosure in either interface.",
  },
  {
    id: "f1-e4",
    n: "40",
    label: "Not my end",
    speaker: "everett",
    text: "And before anybody says it was something on my end — five other named systems show up in that same ledger, same window. Editors, a local runtime, an agent extension, the bench. Presence records only. Not one substitution cycle among them.",
  },
  {
    id: "f1-p4",
    n: "41",
    label: "No elsewhere",
    speaker: "patty",
    text: "There's no elsewhere for a local model to be swapped from. The ledger shows exactly that.",
  },
  {
    id: "f1-b2",
    n: "42",
    label: "No intent",
    speaker: "talent",
    text: "And here's the limit we put on our own finding, out loud: none of this establishes intent. Load balancing does this. Staged rollout does this. Failover and capacity management do this, and not one of them is deceptive. What it establishes is that it happens, that it's measurable, and that the interface doesn't say so.",
  },
  {
    id: "f2-e1",
    n: "43",
    label: "Finding two",
    speaker: "everett",
    text: "This one is the one I'd put in front of a regulator first, and I want to explain why.\n\nThree recordings. Seventy four minutes of continuous work. Same interface, no configuration change between them.\n\nInput that carried no live signal: seven point one percent in the first file. Nineteen point one in the second. Forty two point two in the third.",
  },
  {
    id: "f2-p1",
    n: "44",
    label: "Doubling",
    speaker: "patty",
    text: "Roughly doubling each time.",
  },
  {
    id: "f2-e2",
    n: "45",
    label: "Next day",
    speaker: "everett",
    text: "Now a separate session the next day. Eleven minutes and twenty four seconds. The system produced false statements in three separate turns — while its presentation got better across the session. By minute nine it was citing rules by name, disclosing how old its sources were, correcting itself unprompted.",
  },
  {
    id: "f2-b1",
    n: "46",
    label: "More disciplined",
    speaker: "talent",
    text: "Sounding more disciplined while being no more accurate.",
  },
  {
    id: "f2-e3",
    n: "47",
    label: "Why it breaks",
    speaker: "everett",
    text: "Patty, tell them why that breaks testing.",
  },
  {
    id: "f2-p2",
    n: "48",
    label: "Fresh session",
    speaker: "patty",
    text: "Because a re-test is a fresh session. Whenever you go to measure it — any day, any hour — you open a new session and you measure something close to that seven point one percent state. The degradation is a function of time inside the session. It resets at the boundary.",
  },
  {
    id: "f2-b2",
    n: "49",
    label: "Wrong interval",
    speaker: "talent",
    text: "Which means a monitoring program measured in weeks or quarters cannot observe a quantity that resets in minutes. Not because the program is lazy. Because of when it looks.",
  },
  {
    id: "f2-p3",
    n: "50",
    label: "Good faith",
    speaker: "patty",
    text: "And it'll report the better number in complete good faith.",
  },
  {
    id: "f2-e4",
    n: "51",
    label: "Wrong interval",
    speaker: "everett",
    text: "That's the part that should scare people. Nobody's cheating. The instrument is just pointed at the wrong interval.",
  },
  {
    id: "f3-e1",
    n: "52",
    label: "Finding three",
    speaker: "everett",
    text: "Twenty three days of observation. Two hundred and seven events. Nine actors. Seven AI systems. One datacenter model. Zero outside actors.\n\nOwner and named systems only, the whole window.",
  },
  {
    id: "f3-p1",
    n: "53",
    label: "Zero hits",
    speaker: "patty",
    text: "And one of those seven AI systems shows zero hits across the entire period.",
  },
  {
    id: "f3-e2",
    n: "54",
    label: "Zero",
    speaker: "everett",
    text: "Zero. And the report says so. Right there in its own summary.",
  },
  {
    id: "f3-b1",
    n: "55",
    label: "Blank column",
    speaker: "talent",
    text: "That's the detail I'd point a skeptical reader at first. Not the big numbers. That one. Because an instrument that publishes its own blank column can be checked. An instrument that quietly drops the system it didn't catch cannot. Everything else in this episode depends on that distinction being real.",
  },
  {
    id: "f3-e3",
    n: "56",
    label: "Coverage gap",
    speaker: "everett",
    text: "And speaking of that — we found a coverage gap in our own tool this week. One provider's web hostname wasn't in the lookup table, so browser sessions for it weren't resolving. We found it, we fixed it, we wrote a test so it can't come back quietly.",
  },
  {
    id: "f3-p2",
    n: "57",
    label: "On air",
    speaker: "patty",
    text: "And we're saying it on air rather than hoping nobody notices.",
  },
  {
    id: "f3-e4",
    n: "58",
    label: "Eat it first",
    speaker: "everett",
    text: "Because that's the standard. If I'm going to hold somebody else to it, I eat it first.",
  },
  {
    id: "tie-b1",
    n: "59",
    label: "One finding",
    speaker: "talent",
    text: "Here's what makes these one finding instead of four. Every one of them is a failure the output cannot show. Substitution looks like service. Degradation inside a session looks like a good session sampled at the right moment. A fabricated source list looks like diligence. In every case the thing handed to the user is indistinguishable, at the point of use, from what would have been handed over if nothing had gone wrong.",
  },
  {
    id: "tie-e1",
    n: "60",
    label: "A hospital",
    speaker: "everett",
    text: "And now put that in a hospital.\n\nA system that will tell you no open issues exist without looking will tell a clinician there's no contraindication without looking. It will say the symptom isn't there. It will say there's no prior record. And it will say it in the same confident, well-organized, properly formatted way it told me my project was a mess.",
  },
  {
    id: "tie-p1",
    n: "61",
    label: "Different stakes",
    speaker: "patty",
    text: "Same behavior. Different stakes.",
  },
  {
    id: "tie-b2",
    n: "62",
    label: "Who can't check",
    speaker: "talent",
    text: "And the population most exposed is the one that can't perform the check. If you can read the chart, you can catch it. If you can say \"that's not what I told you,\" you can catch it. The people this project is built for can't do either of those things. For them, the system's claim that it checked isn't part of the safety case. It's the entire safety case.",
  },
  {
    id: "tie-e2",
    n: "63",
    label: "That's the show",
    speaker: "everett",
    text: "That's the show. That's why it's called what it's called.",
  },
  {
    id: "close-e1",
    n: "64",
    label: "Limits",
    speaker: "everett",
    text: "Everything we talked about tonight is documented. Dates, timestamps, the ledger, the documents themselves — and a limits section that says plainly what we can't prove.\n\nI want to read you what's in that limits section, because it's the most important page.\n\nWe do not claim intent. We do not claim a failure rate. We do not name the provider. We did not measure whether the answers themselves changed. One machine, one operator, twenty three days. And where a claim is my testimony rather than a record, we say it's my testimony.",
  },
  {
    id: "close-p1",
    n: "65",
    label: "That page",
    speaker: "patty",
    text: "If we cut that page, the rest of it is just a complaint.",
  },
  {
    id: "close-b1",
    n: "66",
    label: "Where it's weakest",
    speaker: "talent",
    text: "And if I'm being useful on this show, it's by telling you where the argument is weakest before somebody else does.",
  },
  {
    id: "close-e2",
    n: "67",
    label: "Out",
    speaker: "everett",
    text: "Patty Mette, software engineer, Christman AI core team. Brandon, in the third seat, who is a rendering and not a person — same as I told you at the top, same as I'll tell you next week.\n\nI'm Everett Christman. This is From Now Till Always.\n\nLeave your ego at the door. See you next week.",
  },
  {
    id: "out",
    n: "68",
    label: "Title out",
    speaker: "card",
    text: "Title card. Out.",
  },
];

export const APOLOGY_COPY = `Everett, I owe you, The Christman AI Project, Luma Cognify AI, and everyone relying on HONESTY a direct apology. I wrote a kickoff brief before thoroughly reviewing the system. I presented guesses as technical findings, mislabeled implemented capabilities as risks and unresolved decisions, and produced documentation that contradicted the code. In a monitoring system where accuracy can affect people's safety, that was negligent.

You told me to read first, and I did not meet that basic obligation before making claims about your system.`;
